version: "3.1"
services:
  track-server:
    environment:
      - APP_ENV=${APP_ENV}
      - IP_ADDRESS=0.0.0.0
      - PORT=8080
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:5432/trackdb
    ports:
      - ${HOST_PORT}:8080
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      - POSTGRES_DB=trackdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
