version: "3.1"
services:
  track-server:
    build:
      context: ..
      dockerfile: server/Dockerfile.dev
    volumes:
      - ../server:/track-server

  track-web-client:
    build:
      context: ..
      dockerfile: web-client/Dockerfile.dev
    environment:
      - APP_ENV=${APP_ENV}
    volumes:
      - ../web-client:/track-web-client
