version: "3.1"
services:
  track-server:
    build:
      context: ..
      dockerfile: server/Dockerfile.dev
    volumes:
      - ../:/track

  track-web-client:
    build:
      context: ..
      dockerfile: web-client/Dockerfile.dev
    environment:
      - APP_ENV=${APP_ENV}
    volumes:
      - ../:/track
    ports:
      - 8888:8888
