FROM rust:1.73-slim-buster as builder
RUN apt-get update && apt-get install -y build-essential libpq-dev
RUN cargo install diesel_cli --no-default-features --features postgres
WORKDIR /track
CMD ["/track/ops/sleep.sh"]
# CMD ["cargo", "run", "--bin", "server"]
