# Base Builder Stage
FROM rust:1.73-slim-buster as base-builder
WORKDIR /usr/src/app
RUN apt-get update && apt-get install -y build-essential libpq-dev
COPY . .
# RUN cargo fetch  # This fetches all dependencies as per Cargo.lock
RUN cargo build --release # This forces compilation of dependencies

# Upload this to johnshaughnessy/track/track-base-builder
