# Base stage
FROM rust:1.73-slim-buster as base
WORKDIR /usr/src/app
RUN apt-get update && apt-get install -y build-essential libpq-dev
RUN cargo install diesel_cli --no-default-features --features postgres

# Copy migration files
COPY ./migrations /usr/src/app/migrations
