FROM rust:1.73-slim-buster as builder
RUN rustup target add wasm32-unknown-unknown
RUN cargo install trunk
WORKDIR /track
CMD ["/track/ops/sleep.sh"]
# CMD ["trunk", "serve", "web-client/index.html", "--address", "0.0.0.0", "--port", "8888"]
