name: Build server images

on:
  push:
    branches:
      - main

jobs:
  build_docker_image_track_base_builder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Paths Changes Filter
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            lock:
              - 'server/Cargo.lock'

      - id: "auth"
        # if: steps.changes.outputs.lock == 'true'
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: "Set up Cloud SDK"
        # if: steps.changes.outputs.lock == 'true'
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Configure Docker to use Google Artifact Registry
        # if: steps.changes.outputs.lock == 'true'
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Base Builder Image
        # if: steps.changes.outputs.lock == 'true'
        run: |
          cd server
          docker build -f Dockerfile.base-builder --target base-builder -t us-central1-docker.pkg.dev/hubs-dev-333333/ocho-osai/johnshaughnessy/track/track-base-builder .
          docker push us-central1-docker.pkg.dev/hubs-dev-333333/ocho-osai/johnshaughnessy/track/track-base-builder

  build_docker_image_track_server:
    runs-on: ubuntu-latest
    needs: build_docker_image_track_base_builder

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Configure Docker to use Google Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push App Image
        run: |
          cd server
          docker build -t us-central1-docker.pkg.dev/hubs-dev-333333/ocho-osai/johnshaughnessy/track/track-server .
          docker push us-central1-docker.pkg.dev/hubs-dev-333333/ocho-osai/johnshaughnessy/track/track-server

  build_docker_image_track_migration_runner:
    runs-on: ubuntu-latest
    needs: build_docker_image_track_base_builder

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Configure Docker to use Google Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Migration Runner Image
        run: |
          cd server  # Change this to your Dockerfile's directory if needed
          docker build -t us-central1-docker.pkg.dev/hubs-dev-333333/ocho-osai/johnshaughnessy/track/track-migration-runner -f Dockerfile.migration .
          docker push us-central1-docker.pkg.dev/hubs-dev-333333/ocho-osai/johnshaughnessy/track/track-migration-runner
